### PR TITLE
Cleanup, round 2

### PR DESCRIPTION
**Pull request by Arcanemagus**
A bit more cleanup:
* Fix the specs on Windows
* Fix Atom Beta builds

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Looks like that works, now we just wait on the CI builds 😆.

**Comment by Arcanemagus** [comment]
@gmist Do you want to keep this project in CoffeeScript, or should I put up a re-write PR moving it over to modern JS?

**Comment by gmist** [comment]
I would prefer to keep CoffeeScript.

**Comment by Arcanemagus** [comment]
Ha! I was literally just about to click the merge button when it disappeared on me 😉.

**Pull request merged**
