### PR TITLE
non-ascii source code

### PR DESCRIPTION
**Pull request by hamada2029**
Read non-ascii source code.
Thanks to gmist, Compatible python2 and 3.
https://github.com/AtomLinter/linter-pylama/pull/65

### CODE REVIEW

**Comment by ddaanet** [comment]
That's wrong. It assumes the encoding is utf8. If you really need to decode the source (not sure you do, I do have some non-ascii files, but did not notice a problem) then you need to conform to pep263

https://www.python.org/dev/peps/pep-0263/

**Comment by ddaanet** [comment]
I just tested, it works just fine for me with non-ascii source code. You need to explain what actual problem you are trying to fix here.

**Comment by hamada2029** [comment]
Thank you for your response.
I tested on python3 with Japanese characters.

test_jp.py

```
# -*- coding: utf-8 -*-
"""Test Jp."""


def main():
    """Main."""
    print('python')
    print('パイソン')
    print('錦蛇')




# "E303 too many blank lines"
# Should be displayed.
if __name__ == '__main__':
    main()
```


test.py

```
# -*- coding: utf-8 -*-
"""Test."""


def main():
    """Main."""
    print('python')




# "E303 too many blank lines"
# is displayed.
if __name__ == '__main__':
    main()
```

**Comment by ddaanet** [comment]
I see, it's a python3 specific issue. Try configuring the python2 interpreter, and it will go away.

I run python2 here, so no surprise I did not notice the problem.

In a python3 REPL, I tried reading your file both ways, and I get the same result:
```
>>> a = open('test_jp.py', 'rU').read()
>>> b = open('test_jp', 'rUb').read().decode('utf8')
>>> a == b
True
```

Python 3 documentation says:

> As mentioned in the Overview, Python distinguishes between binary and text I/O. Files opened in binary mode (including 'b' in the mode argument) return contents as bytes objects without any decoding. In text mode (the default, or when 't' is included in the mode argument), the contents of the file are returned as str, the bytes having been first decoded using a platform-dependent encoding or using the specified encoding if given.

I guess your system encoding is not UTF-8, hence your problem.

For python2, you could just leave the current behaviour. For Python 3.4+ you can use importlib.util.decode_source.

I say, for 2<python<3.4, just leave the current behaviour. If some reason you need to use an outdated py3, then fix your system encoding.

**Comment by hamada2029** [comment]
I got python3 LANG.
`python3 -c "import os;print(os.environ['LANG'])"` is ja_JP.UTF-8.
But set pylama interpreter to my python3 path (ex. /usr/local/bin/python3), 
os.environ['LANG'] is empty. 
(Mac OS 10.11.6. Similar problem occurred at calling python in applescript.)

So I make shell script file.
```
echo 'LANG=ja_JP.UTF-8 /usr/local/bin/python3 "$@"' > python3_u8.sh
chmod +x python3_u8.sh
```
Set interpreter to python3_u8.sh.
It works without my patch.
Thanks !

**Pull request closed without merging**
