### PR TITLE
Utilize build stages in Travis CI

### PR DESCRIPTION
**Pull request by Arcanemagus**
Update to the current standard config, including using build stages.

Note that testing of beta has been removed from macOS.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Looks like the results are out of order in Python 3.6.

**Comment by gmist** [comment]
> Looks like the results are out of order in Python 3.6.
It's weird... It could happen after upgrading to 3.7 but not in 3.6.

**Comment by Arcanemagus** [comment]
`pylama` is apparently still using the older `pycodestyle`, so it can't even run on Python 3.7 yet.

**Comment by Arcanemagus** [comment]
Looks like that did it 🎉

**Pull request merged**
